window.JL_KANJI = [
  ["一","one",""],["二","two",""],["三","three",""],["四","four",""],["五","five",""],
  ["六","six",""],["七","seven",""],["八","eight",""],["九","nine","baseball"],["十","ten",""],
  ["口","mouth",""],["日","day",""],["月","month",""],["田","rice field",""],["目","eye",""],
  ["古","old",""],["吾","I",""],["冒","risk",""],["朋","companion",""],["明","bright",""],
  ["唱","chant",""],["晶","sparkle",""],["品","goods",""],["呂","spine",""],["昌","prosperous",""],
  ["早","early",""],["旭","rising sun",""],["世","generation",""],["胃","stomach",""],["旦","nightbreak",""],
  ["胆","gall bladder",""],["亘","span",""],["凹","concave",""],["凸","convex",""],["旧","olden days",""],
  ["自","oneself",""],["白","white",""],["百","hundred",""],["中","in",""],["千","thousand",""],
  ["舌","tongue",""],["升","measuring box",""],["昇","rise up",""],["丸","round",""],["寸","measurement",""],
  ["専","specialty",""],["博","Dr.",""],["占","fortune telling",""],["上","above",""],["下","below",""],
  ["卓","eminent",""],["朝","morning",""],["只","only",""],["貝","shellfish",""],["貞","upright",""],
  ["員","employee",""],["見","see",""],["児","newborn babe",""],["元","beginning",""],["頁","page","head"],
  ["頑","stubborn",""],["凡","mediocre",""],["負","defeat",""],["万","ten thousand",""],["句","phrase",""],
  ["肌","texture",""],["旬","decameron",""],["勺","ladle",""],["的","bull's eye",""],["首","neck",""],
  ["乙","fishguts",""],["乱","riot",""],["直","straightaway",""],["具","tool",""],["真","true",""],
  ["工","craft",""],["左","left",""],["右","right",""],["有","possess",""],["賄","bribe",""],
  ["貢","tribute",""],["項","paragraph",""],["刀","sword",""],["刃","blade",""],["切","cut",""],
  ["召","seduce",""],["昭","shining",""],["則","rule",""],["副","vice",""],["別","separate",""],
  ["丁","street","nail or spike"],["町","village",""],["可","can",""],["頂","place on the head",""],["子","child",""],
  ["孔","cavity",""],["了","complete",""],["女","woman",""],["好","fond",""],["如","likeness",""],
  ["母","mama / mother",""],["貫","pierce",""],["兄","elder brother","teenager"],["克","overcome",""],["小","little",""],
  ["少","few",""],["大","large","St. Bernard dog"],["多","many",""],["夕","evening",""],["汐","eventide",""],
  ["外","outside",""],["名","name",""],["石","stone","stone / rocks"],["肖","resemblance","spark or candle"],["硝","nitrate",""],
  ["砕","smash",""],["砂","sand",""],["削","plane",""],["光","ray",""],["太","plump",""],
  ["器","utensil",""],["臭","stinking",""],["妙","exquisite",""],["省","focus",""],["厚","thick",""],
  ["奇","strange",""],["川","stream","flood"],["州","state",""],["順","obey",""],["水","water",""],
  ["氷","icicle",""],["永","eternity",""],["泉","spring",""],["原","meadow",""],["願","petition",""],
  ["泳","swim",""],["沼","marsh",""],["沖","open sea",""],["江","creek",""],["汁","soup",""],
  ["潮","tide",""],["源","source",""],["活","lively",""],["消","extinguish",""],["況","but of course",""],
  ["河","river",""],["泊","overnight",""],["湖","lake",""],["測","fathom",""],["土","soil","dirt, ground, land"],
  ["吐","spit",""],["圧","pressure",""],["埼","cape",""],["垣","hedge",""],["圭","squared jewel","ivy"],
  ["封","seal",""],["涯","horizon",""],["寺","Buddhist temple",""],["時","time",""],["均","level",""],
  ["火","fire","fireplace / hearth / conflagration"],["炎","inflammation",""],["煩","anxiety",""],["淡","thin",""],["灯","lamp",""],
  ["畑","farm",""],["災","disaster",""],["灰","ashes",""],["点","spot",""],["照","illuminate",""],
  ["魚","fish",""],["漁","fishing",""],["里","ri","computer"],["黒","black",""],["墨","black ink",""],
  ["鯉","carp",""],["量","quantity",""],["厘","rin",""],["埋","bury",""],["同","same","monks dressed in a common habit"],
  ["洞","den",""],["胴","trunk",""],["向","yonder",""],["尚","esteem",""],["字","character",""],
  ["守","guard",""],["完","perfect",""],["宣","proclaim",""],["宵","wee hours",""],["安","relax",""],
  ["宴","banquet",""],["寄","draw near",""],["富","wealth",""],["貯","savings",""],["木","tree","wood"],
  ["林","grove",""],["森","forest",""],["桂","Japanese Judas-tree",""],["柏","oak",""],["枠","frame",""],
  ["梢","treetops",""],["棚","shelf",""],["杏","apricot",""],["桐","paulownia",""],["植","plant",""],
  ["枯","wither",""],["朴","crude",""],["村","town",""],["相","inter-",""],["机","desk",""],
  ["本","book",""],["札","tag",""],["暦","calendar",""],["案","plan",""],["燥","parch",""],
  ["未","not yet",""],["末","extremity",""],["沫","splash",""],["味","flavor",""],["妹","younger sister",""],
  ["朱","vermilion",""],["株","stocks",""],["若","young",""],["草","grass",""],["苦","suffering",""],
  ["寛","tolerant",""],["薄","dilute",""],["葉","leaf",""],["模","imitation",""],["漠","vague",""],
  ["墓","grave",""],["暮","livelihood",""],["膜","membrane",""],["苗","seedling",""],["兆","portent","turtle"],
  ["桃","peach tree",""],["眺","stare",""],["犬","dog","small dog"],["状","status quo",""],["黙","silence",""],
  ["然","sort of thing",""],["荻","reed",""],["狩","hunt",""],["猫","cat",""],["牛","cow",""],
  ["特","special",""],["告","revelation",""],["先","before",""],["洗","wash",""],["介","jammed in",""]
].map(function(row,index){
  return {id:index+1,kanji:row[0],meaning:row[1],hint:row[2],answers:row[1].split("/").map(function(value){return value.trim()})};
});
